##代号:[官网显示标题,跳转链接(首页),描述,图片链接,is_disable: True]
#路径含特殊字符如yml原生的? ，需要将整个字符串加引号
title: [name,jump_link,desc,resource,extra]
7.1:
  Index: [Index,null,null,null,null]
  IndexCoDocument: [运营文档,null,null,null,null]
  IndexQuickStart: [iwiki空间首页,https://iwiki.woa.com/space/crosgame,一键直达iwiki空间，获取帮助内容,static/assets/QuickStart.png ,null]
  IndexDeploymtGuides: [接入指南,https://iwiki.woa.com/p/4007009895,接入出海版蓝鲸的流程指引,static/assets/DeploymentGuides.png,null]
  IndexBestPractices: [场景案例,BestPractices/7.1/readme.md,覆盖企业CI、CD、CO场景，从研发到运维、运营的实际案例,static/assets/BestPractices.png,null]
  IndexDevelopGuide: [开发指南,DevelopGuide/7.0/DevelopGuide.md,面向运维的SaaS开发指引，开源及API文档,static/assets/DevelopGuide.png,null]
  IndexVideo: [视频教程,https://bk.tencent.com/s-mart/video,蓝鲸智云品牌介绍、运维开发实战及历届沙龙视频,static/assets/Video.png,null]
  IndexFAQ: [常见问题,https://bk.tencent.com/s-mart/community/question/2194?type=answer,平台部署、日常维护与使用的常见问题,static/assets/FAQ.png,null]
  IndexProdDocument: [产品文档,null,null,null,null]
  IndexIntro: [蓝鲸整体,null,了解蓝鲸智云的品牌价值和产品体系,static/assets/Intro.png,null]
  IndexWhatBlueking: [什么是蓝鲸,BlueKingFamily/7.0/UserGuide/intro.md,null,null,null]
  IndexOnlineGuide: [线上体验环境快速入门,OnlineGuide/7.0/README.md,null,null,null]
  IndexBKNews: [最新公告,ReleaseNotes/7.0/Release.md,null,null,null]
  IndexVersionLog: [版本日志,VersionLog/7.1/v71.md,null,null,null]
  IndexDownloads: [资源下载,downloads/7.0/PPT.md,null,null,null]
  # IndexDocumentationContributorGuide: [共建文档,DocumentationContributorGuide/7.0/rules.md,null,null,null]
  IndexPaaSService: [PaaS层,null,蓝鲸智云可视化开发平台提供了前端页面在线可视化拖拽组装、配置编辑、源码生成、二次开发等能力。旨在帮助用户通过尽量少的手写代码的方式快速设计和开发 SaaS,static/assets/PaaSService.png,null]
  IndexPaaS: [PaaS平台,PaaS/1.0/UserGuide/Overview/README.md,null,null,null]
  IndexAPIGateway: [APIGateway,APIGateway/1.10/UserGuide/README.md,null,null,null]
  IndexSaaSDevelopmentDatabase: [SaaS开发者资料库,PaaS/DevelopTools/BaseGuide/topics/paas/app_intro.md,null,null,null]
  IndexMagicBox: [前端组件MagicBox,https://magicbox.bk.tencent.com/static_api/v3/index.html#start,null,null,null]
  IndexLessCode: [可视化开发平台,LessCode/1.0/UserGuide/intro.md,null,null,null]
#  IndexIntegrateGuide: [集成开发指南,null,null,null,is_disable: True]
  IndexAtomService: [原子平台层,null,聚焦原子平台核心功能，助力企业夯实底层平台能力,static/assets/AtomService.png,null]
  IndexCMDB: [配置平台,CMDB/3.10/UserGuide/Introduce/Overview.md,null,null,null]
  IndexGSE: [管控平台,GSE/2.0/UserGuide/Introduce.md,null,null,null]
  IndexJOB: [作业平台,JOB/3.7/UserGuide/Introduction/What-is-Job.md,null,null,null]
  IndexBCS: [容器管理平台,BCS/1.28/UserGuide/Introduction/README.md,null,null,null]
  IndexUserManage: [用户管理,UserManage/2.5/UserGuide/Introduce/README.md,null,null,null]
  IndexIAM: [权限中心,IAM/1.12/UserGuide/Introduce/README.md,null,null,null]
  IndexDevops: [持续集成平台,Devops/2.0/UserGuide/intro/README.md,null,null,null]
  IndexBKBase: [计算平台,BK-Base/3.10/UserGuide/Introduction/intro.md,null,null,null]
  IndexSaaSService: [SaaS场景层,null,内容丰富的SaaS产品，开箱即用,static/assets/SaaSService.png,null]
  IndexNodeMan: [节点管理,NodeMan/2.2/UserGuide/Introduce/Overview.md,null,null,null]
  IndexSOPS: [标准运维,SOPS/3.28/UserGuide/Overview/README.md,null,null,null]
  IndexMonitor: [监控平台,Monitor/3.8/UserGuide/Overview/README.md,null,null,null]
  IndexLogSearch: [日志平台,LogSearch/4.6/UserGuide/Intro/README.md,null,null,null]
  IndexITSM: [流程服务,ITSM/2.6/UserGuide/Introduce/README.md,null,null,null]
#  IndexAuditCenter: [审计中心,null,null,null,is_disable: True]
#  IndexDBManage: [DB管理平台,null,null,null,is_disable: True]
#  IndexChartPlatform: [图表平台,null,null,null,is_disable: True]
#  IndexHaiLei: [海垒,null,null,null,is_disable: True]
#  # IndexGSEKit: [进程配置管理,null,null,null,is_disable: True]
  Doc: [Doc,null,null,null,null]
  DocProdDocument: [产品文档,null,null,null,null]
  DocBrandConcept: [品牌理念,BlueKingFamily/7.0/UserGuide/intro.md,null,null,null]
  DocBlueKingFamily: [蓝鲸体系,BlueKingFamily/7.0/UserGuide/Solution/solution.md,null,null,null]
  DocAtomService: [蓝鲸平台层,null,null,null,null]
  DocPaaS: [PaaS平台,PaaS/1.0/UserGuide/Overview/README.md,null,null,null]
  DocCMDB: [配置平台,CMDB/3.10/UserGuide/Introduce/Overview.md,null,null,null]
  DocJOB: [作业平台,JOB/3.7/UserGuide/Introduction/What-is-Job.md,null,null,null]
  DocGSE: [管控平台,GSE/2.0/UserGuide/Introduce.md,null,null,null]
  DocBCS: [容器管理平台,BCS/1.28/UserGuide/Introduction/README.md,null,null,null]
  DocUserManage: [用户管理,UserManage/2.5/UserGuide/Introduce/README.md,null,null,null]
  DocIAM: [权限中心,IAM/1.12/UserGuide/Introduce/README.md,null,null,null]
  DocDevops: [持续集成平台,Devops/2.0/UserGuide/intro/README.md,null,null,null]
  DocBKBase: [计算平台,null,null,null,is_disable: True]
  DocAPIGateway: [APIGateway,APIGateway/1.10/UserGuide/README.md,null,null,null]
  DocLessCode: [可视化开发平台,LessCode/1.0/UserGuide/intro.md,null,null,null]
  DocSaaSService: [SAAS场景层,null,null,null,null]
  DocNodeMan: [节点管理,NodeMan/2.2/UserGuide/Introduce/Overview.md,null,null,null]
  DocSOPS: [标准运维,SOPS/3.28/UserGuide/Overview/README.md,null,null,null]
  DocMonitor: [监控平台,Monitor/3.8/UserGuide/Overview/README.md,null,null,null]
  DocLogSearch: [日志平台,LogSearch/4.6/UserGuide/Intro/README.md,null,null,null]
  DocITSM: [流程服务,ITSM/2.6/UserGuide/Introduce/README.md,null,null,null]
#  DocAuditCenter: [审计中心,null,null,null,is_disable: True]
#  DocDBManage: [DB管理平台,null,null,null,is_disable: True]
#  DocChartPlatform: [图表平台,null,null,null,is_disable: True]
#  DocHaiLei: [海垒,null,null,null,is_disable: True]
#  # DocGSEKit: [进程配置管理,null,null,null,is_disable: True]
  # DocQuickUse: [快速入门,null,null,null,null]
  # DocQuickStart: [快速使用,QuickStart/7.0/quick-start-v7.0-info.md,null,null,null]
  # DocOnlineGuide: [蓝鲸线上体验环境快速入门,OnlineGuide/7.0/README.md,null,null,null]
  # DocSceneCase: [场景案例,null,null,null,null]
  # DocCIIntegration: [基础套餐,BestPractices/7.1/BASIC/CMDB-HowToCreateTopo.md,null,null,null]
  # DocCDDeploy: [监控日志套餐,BestPractices/7.1/Monitor/Monitor-HowCanHostBasicBeMonitoring.md,null,null,null]
  # DocCOOperate: [容器管理套餐,BestPractices/7.0/CO/ITSM/Incident_Management.md,null,null,null]
  DocDevelopGuide: [开发指南,null,null,null,null]
  DocDevelopStandard: [开发规范,DevelopGuide/DevSpecification/FrontendDevSpec/README.md,null,null,null]
  DocSaaSDeveloperDatabase: [SaaS开发者资料库,PaaS/DevelopTools/BaseGuide/topics/paas/app_intro.md,null,null,null]
  DocFrontTools: [前端组件MagicBox,https://magicbox.bk.tencent.com/static_api/v3/index.html#start,null,null,null]
#  DocIntegrateGuide: [集成开发指南,null,null,null,is_disable: True]
  DocErrorCode: [蓝鲸错误码,DevelopGuide/7.0/ErrorCodeIndex.md,null,null,null]
  DocAPIDocument: [API文档,DevelopGuide/7.0/APIIndex.md,null,null,null]
  DocDeploymentMaint: [部署维护,null,null,null,null]
  DocKeSBead: [准备资源及环境,DeploymentGuides/7.1/prepare.md,null,null,null]
  DocBasicMenuDeployment: [部署基础套餐,DeploymentGuides/7.1/install-bkce.md,null,null,null]
  DocBCSDeploy: [容器管理平台部署,DeploymentGuides/7.1/install-bcs.md,null,null,null]
  DocMonitorDeploy: [监控日志套餐部署,DeploymentGuides/7.1/install-co-suite.md,null,null,null]
  DocDevopsDeploy: [持续集成套餐部署,DeploymentGuides/7.1/install-ci-suite.md,null,null,null]
  DocLessCodeDeploy: [可视化开发平台安装指引,DeploymentGuides/7.1/install-lesscod.md,null,null,null]
  DocUninstall: [卸载,DeploymentGuides/7.1/uninstall.md,null,null,null]
  DocFAQ: [FAQ,DeploymentGuides/7.1/faq.md,null,null,null]
  DocCommonInformation: [常用信息,null,null,null,null]
  DocNews: [最新公告,ReleaseNotes/7.0/Release.md,null,null,null]
  DocVersionLog: [版本日志,VersionLog/7.1/v71.md,null,null,null]
  DocDownloadResources: [资源下载,downloads/7.0/PPT.md,null,null,null]
  DocDocumentationContributorGuide: [共建文档,DocumentationContributorGuide/7.0/rules.md,null,null,null]